# Generated by Django 4.2.8 on 2023-12-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyclass',
            name='user',
        ),
        migrations.AddField(
            model_name='studyclass',
            name='supabase_user_id',
            field=models.UUIDField(default=0),
        ),
    ]
