# Generated by Django 4.2.8 on 2023-12-30 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_remove_studyclass_user_studyclass_supabase_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flashcard',
            new_name='FlashCards',
        ),
    ]
