# Generated by Django 4.2.8 on 2024-01-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_rename_flashcard_flashcards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyclass',
            name='supabase_user_id',
        ),
        migrations.AddField(
            model_name='studyclass',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
