# Generated by Django 4.2.8 on 2024-02-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_alter_studyclass_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyclass',
            name='user_id',
            field=models.CharField(max_length=96),
        ),
    ]
