# Generated by Django 4.2.8 on 2024-02-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0007_rename_user_id_studyclass_user_id_or_study_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardset',
            name='description',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='flashcardset',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
