# Generated by Django 4.2.8 on 2024-02-24 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0008_flashcardset_description_alter_flashcardset_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcardset',
            old_name='title',
            new_name='name',
        ),
    ]
