# Generated by Django 4.2.8 on 2024-02-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0009_rename_title_flashcardset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardset',
            name='description',
            field=models.CharField(blank=True, default='', max_length=40),
            preserve_default=False,
        ),
    ]
