# Generated by Django 4.2.8 on 2024-02-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0012_alter_flashcardset_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardset',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
