# Generated by Django 4.2.8 on 2024-03-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0014_alter_studyclass_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardset',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
