# Generated by Django 4.2.8 on 2024-05-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0015_alter_flashcardset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcards',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='studyclass',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
