# Generated by Django 4.2.8 on 2024-05-08 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0016_flashcards_created_at_flashcardset_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcards',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 8, 20, 46, 40, 664817, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flashcardset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 8, 20, 46, 45, 852240, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studyclass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 8, 20, 46, 48, 306775, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
