version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - ./frontend:/frontend

volumes:
  postgres_data: # This can be removed if not used anymore
